name: Metrics
on:
  schedule: [{cron: "0 12 * * 1"}] # Corre los lunes a las 12
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: "header, activity, community, repositories"
          config_timezone: America/Argentina/Buenos_Aires
